version: '3.8'
services:
  kafka:
    image: apache/kafka:4.1.1
    container_name: kafka
    restart: always
    privileged: true
    ports:
      - "${KAFKA_EXTERNAL_PORT:-9092}:9094"
    environment:
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://${KAFKA_EXTERNAL_HOST:-172.16.1.172}:${KAFKA_EXTERNAL_PORT:-9092}
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@${KAFKA_HOST:-kafka}:9093
      - CLUSTER_ID=kYydZq1wR7aZGr4H7FDv5w
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
    volumes:
      - kafka-data:/var/lib/kafka/data
    networks:
      - kafka-net

  kafka-ui:
    restart: always
    privileged: true
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "${KAFKA_UI_PORT:-10180}:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=${KAFKA_HOST:-kafka}:9092
    depends_on:
      - kafka
    networks:
      - kafka-net

volumes:
  kafka-data:
    driver: local

networks:
  kafka-net:
    driver: bridge
