-- 创建用户 HTSP
CREATE USER HTSP IDENTIFIED BY "Weidehua@678678";

-- 创建模式 HTSP_BUSSINESS
CREATE SCHEMA HTSP_BUSSINESS AUTHORIZATION HTSP;

-- 授予权限
GRANT CONNECT, RESOURCE, DBA TO HTSP;
GRANT ALL PRIVILEGES TO HTSP;

-- 提交事务
COMMIT;