version: '3.8'

services:
  jenkins-controller:
    #image: jenkins/jenkins:lts
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jenkins-controller
    ports:
      - "14080:8080"
      - "50000:50000"
    volumes:
      - ./jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock      # 挂载宿主机 Docker sock
    networks:
      - jenkins
    environment:
      - JENKINS_OPTS=--httpPort=8080
      - HTTP_PROXY=http://host.docker.internal:7890
      - HTTPS_PROXY=http://host.docker.internal:7890
      - NO_PROXY=localhost,127.0.0.1
      - http_proxy=http://host.docker.internal:7890
      - https_proxy=http://host.docker.internal:7890
      - no_proxy=localhost,127.0.0.1
    restart: unless-stopped
    user: root

volumes:
  jenkins-data:
  jenkins-agent-workspace:
  jenkins-docker-certs:


networks:
  jenkins:
    driver: bridge

