version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-dev
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 123456         # root 用户密码
      MYSQL_DATABASE: testdb                # 初始化的数据库名
      MYSQL_USER: crab                   # 初始化的普通用户
      MYSQL_PASSWORD: xg678678            # 普通用户密码
    ports:
      - "3306:3306"                          # 映射到主机
    volumes:
      - mysql_data:/var/lib/mysql           # 数据持久化
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  mysql_data:
