version: '3.8'

services:
  crab-mysql:
    image: mysql:8.0
    container_name: crab-mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: go_chat
      MYSQL_USER: crab
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_HOST: '%'
      TZ: Asia/Shanghai
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - iam-network
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -u root -p123456"]
      interval: 10s
      timeout: 5s
      retries: 3

  crab-redis:
    image: redis:7.2-alpine
    container_name: crab-redis
    restart: unless-stopped
    command: >
      redis-server 
      --requirepass "123456" 
      --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - iam-network
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "123456", "ping"]

  crab-minio:
    image: minio/minio:latest
    container_name: crab-minio
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin  #
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - iam-network

volumes:
  mysql_data:
  redis_data:
  minio_data:

networks:
  iam-network:
    driver: bridge